# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- script: |
    choco install packer
    choco install git -params '"/GitAndUnixToolsOnPath"'
  displayName: 'Install packer'

- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'lev'
    ScriptType: 'InlineScript'
    Inline: |
      Set-Location runner-images
      Import-Module .\helpers\GenerateResourcesAndImage.ps1
      $PSNativeCommandArgumentPassing = 'Legacy'
      GenerateResourcesAndImage -subscriptionid "70781410-ee03-4e2b-a97e-b2a55b88bf95" -resourcegroupname "lev-rg-adopipelineimage" -azurelocation "East US" -imagetype "UbuntuMinimal"
    azurePowerShellVersion: 'LatestVersion'